#!/usr/bin/env python3
import argparse
import re
from pathlib import Path

def bump(ver: str) -> str:
    # Accept "x.y.z" (ignore anything after z)
    m = re.match(r"^\s*(\d+)\.(\d+)\.(\d+)\s*$", ver)
    if not m:
        raise SystemExit(f"version.txt must be 'x.y.z' (got: {ver!r})")
    maj, minor, patch = map(int, m.groups())
    patch += 1
    return f"{maj}.{minor}.{patch}"

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--version-file", required=True)
    ap.add_argument("--out-header", required=True)
    args = ap.parse_args()

    vf = Path(args.version_file)
    out_h = Path(args.out_header)

    cur = vf.read_text(encoding="utf-8").strip()
    new = bump(cur)
    vf.write_text(new + "\n", encoding="utf-8")

    out_h.write_text(
        "// Auto-generated by yaota_bump_version.py\n"
        "#pragma once\n"
        f"#define YAOTA_BUILD_VERSION \"{new}\"\n",
        encoding="utf-8",
    )
    print(f"yaotau: bumped {cur} -> {new}")
    print(f"yaotau: wrote {out_h}")

if __name__ == "__main__":
    main()
